### ISSUE TITLE
发送消息失败的问题

### ISSUE THREAD

**Issue by Rekoe** [yangshare/svn2dingding#1]
```
{"errmsg":"robot type do not match with the message","errcode":300001}
```
请问遇到这问题么

**Comment by yangshare** [comment]
@Rekoe 你svn服务器post-commit里面串接字符的格式大概这样：
`set REPOS=%1
set REV=%2
set tttt=%date:~0,10% %time:~0,8%
for /f "tokens=1,2 delims=:" %%a in ('svnlook author -r %REV% %REPOS%') do (
    if not defined AUTHOR set AUTHOR=%%a
)
for /f "tokens=1,2 delims=:" %%a in ('svnlook dirs-changed %REPOS%') do (
    if not defined CHANGEDDIRS set CHANGEDDIRS=%%a
)
for /f "tokens=1,2 delims=:" %%a in ('svnlook log -r %REV% %REPOS%') do (
    if not defined MESSAGE set MESSAGE=%%a
)
set CONTENT="提交时间：%tttt% \n提交版本：%REV% \n作者：%AUTHOR%\n 提交备注：%MESSAGE%\n修改目录：%CHANGEDDIRS% "
java -jar E:\svn2dingdingRobot\request.jar  （此处为tokenID） %CONTENT%`

你看你的Request.java文件：
`content = "{\"msgtype\": \"text\",\"text\": {\"content\": \""+content+"\"},\"at\": {\"isAtAll\": true}}";`
，我这里消息格式是text的。你别json也直接照搬这句，看钉钉怎么配置消息的[https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.rmClMA&treeId=257&articleId=105735&docType=1](url)

**Comment by Rekoe** [comment]
谢谢
